services:
  ros2:
    build: .
    container_name: hand_robot
    volumes:
      - ./ros2_ws/src:/root/ros2_ws/src
      - ./weights:/root/ros2_ws/weights
    working_dir: /root/ros2_ws
    tty: true
    stdin_open: true