services:
  ros2:
    build: .
    container_name: object_tracking_robot
    volumes:
      - ./ros2_ws:/root/ros2_ws
    env_file:
      - ./.env
    working_dir: /root/ros2_ws
    tty: true
    stdin_open: true
    network_mode: host
    ports:
      - "9090:9090"
    privileged: true
    devices:
      - "/dev/gpiomem4:/dev/gpiomem4"