services:
  ros2:
    build: .
    container_name: hand_robot
    volumes:
      - ./ros2_ws/src:/root/ros2_ws/src
      - ./weights:/root/ros2_ws/weights
      - ./.env:/root/ros2_ws/.env:ro
    working_dir: /root/ros2_ws
    tty: true
    stdin_open: true
    # network_mode: host
    ports:
      - "9090:9090"